
trigger:
- master

strategy:
 matrix:
  linux:
    operatingSystem: 'ubuntu-latest'
  mac:
    operatingSystem: 'macos-latest'




pool:
  vmImage: $(operatingSystem)


stages:
- stage: Build
  jobs:
  - job: Build Job
    steps:
    - bash: echo "Do the build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    startegy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    startegy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to QA



